# Density - table of variables of LB Node to stream
#  name - variable name to stream
#  dx,dy,dz - direction of streaming
#  comment - additional comment
#	Velocity-based Evolution d3q27:
AddDensity( name="g[0]", dx= 0, dy= 0, dz= 0, group="g")
AddDensity( name="g[1]", dx= 1, dy= 0, dz= 0, group="g")
AddDensity( name="g[2]", dx=-1, dy= 0, dz= 0, group="g")
AddDensity( name="g[3]", dx= 0, dy= 1, dz= 0, group="g")
AddDensity( name="g[4]", dx= 0, dy=-1, dz= 0, group="g")
AddDensity( name="g[5]", dx= 0, dy= 0, dz= 1, group="g")
AddDensity( name="g[6]", dx= 0, dy= 0, dz=-1, group="g")
AddDensity( name="g[7]", dx= 1, dy= 1, dz= 1, group="g")
AddDensity( name="g[8]", dx=-1, dy= 1, dz= 1, group="g")
AddDensity( name="g[9]", dx= 1, dy=-1, dz= 1, group="g")
AddDensity( name="g[10]",dx=-1, dy=-1, dz= 1, group="g")
AddDensity( name="g[11]",dx= 1, dy= 1, dz=-1, group="g")
AddDensity( name="g[12]",dx=-1, dy= 1, dz=-1, group="g")
AddDensity( name="g[13]",dx= 1, dy=-1, dz=-1, group="g")
AddDensity( name="g[14]",dx=-1, dy=-1, dz=-1, group="g")
AddDensity( name="g[15]",dx= 1, dy= 1, dz= 0, group="g")
AddDensity( name="g[16]",dx=-1, dy= 1, dz= 0, group="g")
AddDensity( name="g[17]",dx= 1, dy=-1, dz= 0, group="g")
AddDensity( name="g[18]",dx=-1, dy=-1, dz= 0, group="g")
AddDensity( name="g[19]",dx= 1, dy= 0, dz= 1, group="g")
AddDensity( name="g[20]",dx=-1, dy= 0, dz= 1, group="g")
AddDensity( name="g[21]",dx= 1, dy= 0, dz=-1, group="g")
AddDensity( name="g[22]",dx=-1, dy= 0, dz=-1, group="g")
AddDensity( name="g[23]",dx= 0, dy= 1, dz= 1, group="g")
AddDensity( name="g[24]",dx= 0, dy=-1, dz= 1, group="g")
AddDensity( name="g[25]",dx= 0, dy= 1, dz=-1, group="g")
AddDensity( name="g[26]",dx= 0, dy=-1, dz=-1, group="g")

#	Phase Field Evolution d3q15:
AddDensity( name="h[0]", dx= 0, dy= 0, dz= 0, group="h")
AddDensity( name="h[1]", dx= 1, dy= 0, dz= 0, group="h")
AddDensity( name="h[2]", dx=-1, dy= 0, dz= 0, group="h")
AddDensity( name="h[3]", dx= 0, dy= 1, dz= 0, group="h")
AddDensity( name="h[4]", dx= 0, dy=-1, dz= 0, group="h")
AddDensity( name="h[5]", dx= 0, dy= 0, dz= 1, group="h")
AddDensity( name="h[6]", dx= 0, dy= 0, dz=-1, group="h")
AddDensity( name="h[7]", dx= 1, dy= 1, dz= 1, group="h")
AddDensity( name="h[8]", dx=-1, dy= 1, dz= 1, group="h")
AddDensity( name="h[9]", dx= 1, dy=-1, dz= 1, group="h")
AddDensity( name="h[10]",dx=-1, dy=-1, dz= 1, group="h")
AddDensity( name="h[11]",dx= 1, dy= 1, dz=-1, group="h")
AddDensity( name="h[12]",dx=-1, dy= 1, dz=-1, group="h")
AddDensity( name="h[13]",dx= 1, dy=-1, dz=-1, group="h")
AddDensity( name="h[14]",dx=-1, dy=-1, dz=-1, group="h")

AddDensity(name="U", dx=0, dy=0, dz=0, group="h")
AddDensity(name="V", dx=0, dy=0, dz=0, group="h")
AddDensity(name="W", dx=0, dy=0, dz=0, group="h")

AddField('PhaseF',stencil3d=1, group="OrderParameter")

# Stages - processes to run for initialisation and each iteration
AddStage("PhaseInit"    , "Init", save="PhaseF")
AddStage("BaseInit"     , "Init_distributions", save=Fields$group=="g" | Fields$group=="h" )
AddStage("calcPhase"	, "calcPhaseF",	save='PhaseF'                             , 
	load=DensityAll$group=="h")
AddStage("BaseIter"     , "Run" , save=Fields$group=="g" | Fields$group=="h" , 
	load=DensityAll$group=="g" | DensityAll$group=="h")

AddAction("Iteration", c("BaseIter", "calcPhase"))
AddAction("Init"     , c("PhaseInit", "BaseInit", "calcPhase"))

# 	Outputs:
AddQuantity(name="Rho",	  unit="kg/m3")
AddQuantity(name="PhaseField",unit="1")
AddQuantity(name="U",	  unit="m/s",vector=T)
AddQuantity(name="P",	  unit="Pa")
#AddQuantity(name="InterfaceForce", unit="N",vector=T)
#	Inputs: For phasefield evolution
AddSetting(name="Density_h", comment='High density')
AddSetting(name="Density_l", comment='Low  density')
AddSetting(name="PhaseField_h", default=1, comment='PhaseField in Liquid')
AddSetting(name="PhaseField_l", default=0, comment='PhaseField gas')
AddSetting(name="PhaseField", 	   comment='Initial PhaseField distribution', zonal=T)
AddSetting(name="Width", default=4,    comment='Anti-diffusivity coeff')
AddSetting(name="omega_phi", comment='one over relaxation time (phase field)')
AddSetting(name="M", omega_phi='1.0/(3*M+0.5)', default=0.02, comment='Mobility')
AddSetting(name="sigma", 		   comment='surface tension')
# 	Inputs: Fluid Properties
AddSetting(name="tau_l", comment='relaxation time (low density fluid)')
AddSetting(name="tau_h", comment='relaxation time (high density fluid)')
AddSetting(name="Viscosity_l", tau_l='(3*Viscosity_l)', default=0.16666666, comment='kinematic viscosity')
AddSetting(name="Viscosity_h", tau_h='(3*Viscosity_h)', default=0.16666666, comment='kinematic viscosity')
#AddSetting(name="S0", default=1.0, comment='Relaxation Param')
#AddSetting(name="S1", default=1.0, comment='Relaxation Param')
#AddSetting(name="S2", default=1.0, comment='Relaxation Param')
#AddSetting(name="S3", default=1.0, comment='Relaxation Param')
#AddSetting(name="S4", default=1.0, comment='Relaxation Param')
#AddSetting(name="S5", default=1.0, comment='Relaxation Param')
#AddSetting(name="S6", default=1.0, comment='Relaxation Param')
#	Inputs: Flow Properties
AddSetting(name="VelocityX", default=0.0, comment='inlet/outlet/init velocity', zonal=T)
AddSetting(name="VelocityY", default=0.0, comment='inlet/outlet/init velocity', zonal=T)
AddSetting(name="VelocityZ", default=0.0, comment='inlet/outlet/init velocity', zonal=T)
AddSetting(name="Pressure" , default=0.0, comment='inlet/outlet/init density', zonal=T)
AddSetting(name="GravitationX", default=0.0, comment='applied (rho)*GravitationX')
AddSetting(name="GravitationY", default=0.0, comment='applied (rho)*GravitationY')
AddSetting(name="GravitationZ", default=0.0, comment='applied (rho)*GravitationZ')
AddSetting(name="BuoyancyX", default=0.0, comment='applied (rho-rho_h)*BuoyancyX')
AddSetting(name="BuoyancyY", default=0.0, comment='applied (rho-rho_h)*BuoyancyY')
AddSetting(name="BuoyancyZ", default=0.0, comment='applied (rho-rho_h)*BuoyancyZ')
# Globals - table of global integrals that can be monitored and optimized
AddGlobal(name="PressureLoss", comment='pressure loss', unit="1mPa")
AddGlobal(name="OutletFlux", comment='pressure loss', unit="1m2/s")
AddGlobal(name="InletFlux", comment='pressure loss', unit="1m2/s")
AddGlobal(name="TotalDensity", comment='Mass conservation check', unit="1kg/m3")
